### ISSUE TITLE
All Months are 31 days

### ISSUE THREAD

**Issue by ronshapiro** [marklarr/SwiftDate#1]
https://github.com/marklarr/SwiftDate/blob/d7097dec5553777ba2adbf9b0cf62573fe516c67/SwiftDate/Extensions/NSTimeInterval.swift#L27

**Comment by marklarr** [comment]
lol

**Comment by ayanonagon** [comment]
LOL

**Comment by magni-** [comment]
If you want to be consistent with Rails, they default to 30:
http://apidock.com/rails/v4.1.8/Integer/months

**Comment by marklarr** [comment]
Rails is dead. Long live SwiftDate!

**Comment by ayanonagon** [comment]
:octocat: :thought_balloon: ...says the Ruby developer.

**Comment by marklarr** [comment]
I've opened up another serious issue

https://github.com/marklarr/SwiftDate/issues/2

**Comment by ronshapiro** [comment]
You put in a fair amount of work for a library that will never be good enough to use :trophy:

**Comment by marklarr** [comment]
Glad we could finally put this issue to rest, @ronshapiro

**Comment by ronshapiro** [comment]
I gave up on Swift entirely so TBH I was kinda happy to close this before
the fix. Down with Swift apps!
